version: '2'
services:
  nginx:
    build: docker/nginx
    links:
      - php
    ports:
      - ${IP_ADDRESS}:80:80
    volumes_from:
      - php
  php:
    build: docker/php
    links:
      - db:db.${PROJECT}.dev
      - mailhog
      - redis
      - solr
    volumes:
      - .:/var/www/html
  db:
    image: mariadb
    environment:
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: root
    ports:
      - ${IP_ADDRESS}:3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      UPLOAD_SIZE: 1G
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - db
    ports:
      - ${IP_ADDRESS}:8080:80
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - ${IP_ADDRESS}:8025:8025
  redis:
    image: redis
  solr:
    image: solr
    ports:
      - ${IP_ADDRESS}:8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
